config/routes.rb
Rails.application.routes.draw do
  get 'audios/show'

  root to: "welcome#index"
  
  resources :cats, only: [:index, :show] do
    resource :audio, only: [:show]
    resources :reservations, only: [:create, :new]
    resources :open_slots, only: [:show], param: :date
  end
  
  namespace :admin do
    resources :reservations, only: [:index]
    resources :cats, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  
  get "/admin", to: "admin/dashboards#index"
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  has_many :reservations, dependent: :destroy
  
  validates :name, presence: true

  # Attach cat image
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  
  # Compute open time slots for cat reservation
  def open_slots(date)
    time = date.to_time
    
    slots = []
    prev_time = time - 30.minutes
    loop do
      start_time = prev_time + 30.minutes
      
      if start_time.to_date == date
        slots << Slot.new(starts_at: start_time, cat: self)
        prev_time = start_time
      else
        break
      end
    end
    
    # Remove taken/past timeframes
    slots.reject do |slot|
      Reservation.exists?(cat: self, starts_at: slot.starts_at) || slot.starts_at.past?
    end
  end
  
  # Render open time slots
  def open_slots_for_select(date)
    open_slots(date).map do |slot|
      ["#{slot.starts_at.strftime('%d/%m/%Y, %H:%M ')}", slot.starts_at]
    end
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  DURATION = 30.minutes
  
  validates :cat_id, :starts_at, :name, :email, presence: true
  
  belongs_to :cat, required: true
  
  # The time the reservation ends at
  def ends_at
    starts_at + DURATION
  end
end

app/models/slot.rb
class Slot
  def initialize(starts_at:, cat:)
    @starts_at = starts_at
    @cat = cat
  end
  
  attr_reader :starts_at
  
  # The time the slot ends
  def ends_at
    @starts_at + Reservation::DURATION
  end
  
  # Create reservation with given `name` and `email`
  def reserve(name:, email:)
    Reservation.create!(name: name, email: email, cat: @cat, starts_at: @starts_at)
  end
end

app/controllers/admin/admin_controller.rb
module Admin
  # Admin autentification
  class AdminController < ApplicationController
    http_basic_authenticate_with name: ENV.fetch("admin_username"), password: ENV.fetch("admin_password")
  end
end

app/controllers/admin/cats_controller.rb
# Controller to administrate cats
module Admin
  class CatsController < AdminController
    # Display all cats
    def index
      @cats = Cat.all
    end
    
    # Render cat creation template
    def new
      @cat = Cat.new
    end
    
    # Create a new cat
    def create
      @cat = Cat.new(cat_params)
    
      if @cat.save
        redirect_to @cat
      else
        render :new
      end
    end
    
    # Render edit cat template
    def edit
      @cat = Cat.find(params[:id])
    end
    
    # Update cat's information
    def update
      @cat = Cat.find(params[:id])
    
      if @cat.update(cat_params)
        redirect_to @cat
      else
        # Render "edit" template:
        render :edit
      end
    end
    
    # Delete cat
    def destroy
      cat = Cat.find(params[:id])
      cat.destroy
      redirect_to cats_path
    end
    
    private
    
    def cat_params
      params.require(:cat).permit(
        :name,
        :male,
        :birthdate,
        :picture,
        :description
      )
    end
  end
end

app/controllers/admin/dashboards_controller.rb
module Admin
  class DashboardsController < AdminController
    # Render dashboard template
    def index
    end
  end
end

app/controllers/admin/reservations_controller.rb
module Admin
  class ReservationsController < AdminController
    # Show all future cat reservations
    def index
      @reversations_on_dates = Reservation
        .where("starts_at > ?", Date.yesterday)
        .order(:starts_at).group_by do |reservation|
          reservation.starts_at.to_date
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  # Render audio from description
  def show
    @cat = Cat.find(params[:cat_id])
    @path = "#{@cat.id}-cat.wav"
    
    username = ENV.fetch("watson_username")
    password = ENV.fetch("watson_password")
    
    worked = system(<<-EOS)
      curl -X POST -u #{username}:#{password} --header "Content-Type: application/json" --header "Accept: audio/wav" --data "{\\"text\\":\\"#{@cat.description}\\"}" --output public/#{@path} "https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize"
    EOS
    
    unless worked
      raise "Didn't work"
    end
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  # Display all cats
  def index
    @cats = Cat.all
  end
  
  # Display individual cat
  def show
    @cat = Cat.find(params[:id])
  end
end

app/controllers/open_slots_controller.rb
class OpenSlotsController < ApplicationController
  # Render correct available timeslots according to chosen cat and day
  def show
    cat = Cat.find(params[:cat_id])
    date = Date.parse(params[:date])
    slots = cat.open_slots_for_select(date)
    html = view_context.options_for_select(slots)
    
    render html: html
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # Render new reservation template
  def new
    @cat = Cat.find(params[:cat_id])
    @reservation = @cat.reservations.new
  end
  
  # Create a new cat reservation
  def create
    cat = Cat.find(params[:cat_id])
    
    reservation_params = params.require(:reservation).permit(:name, :email, :starts_at)
    @reservation = cat.reservations.new(reservation_params)
    
    if @reservation.save
      # Send confiramtion email on successful booking
      ReservationMailer.confirmation_email(@reservation).deliver_later
      
      flash.notice = "Check your email for your reservation info!"
      redirect_to cat
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # Render "Comic of the Week" service
  def index
    @comic = JSON.parse(RestClient.get("http://xkcd.com/info.0.json"))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/cats/_form.html.erb
<%= form_for [:admin, cat], :html => { :multipart => true } do |f| %>
  <div class="form-group">
  	<%= f.label :name%>
  	<%= f.text_field :name, class: "form-control" %>
  </div>
  
  <div>
  	<%= f.label :male, "Male?"%><br>
  	<%= f.check_box :male %>
  	<span>Uncheck if cat female</span>
  </div>
  	<br>
  <div class="form-group">	
  	<%= f.label :birthdate%>
  	<%= f.date_field :birthdate, class: "form-control" %>
  </div>
  <div class="form-group">	
  	<%= f.label :picture %>
  	<%= f.file_field :picture, class: "form-control" %>
  </div>
  <div class="form-group">	
  	<%= f.label :description%>
  	<%= f.text_area :description, class: "form-control" %>
  </div>	
	
  <%= f.submit :class => 'btn btn-primary btn-lg' %>
<% end %>

app/views/admin/cats/edit.html.erb
<%= render partial: "form", locals: { cat: @cat } %>

app/views/admin/cats/index.html.erb
<!--rememebr new cat -->
<% if @cats.present? %>
<ul class="admin-cat-list">
	<% @cats.each do |cat| %>
	<li>
		<div class="cat-picture cat-pic-small" style="background: url('<%= cat.picture.url %>') no-repeat center center;"></div>
		
		<%= link_to cat.name, cat, class: "name" %>
		<%= link_to "Edit", edit_admin_cat_path(cat), class: "btn btn-default" %>
		<%= link_to "Delete", [:admin, cat], method: :delete, data: { confirm: "Sure?" }, class: "btn btn-default" %>
	</li>
	<% end %>
	
</ul>
<% else %>
	<p> There are no cats yet.</p>
<% end %>

app/views/admin/cats/new.html.erb
<%= render partial: "form", locals: { cat: @cat } %>

app/views/admin/dashboards/index.html.erb
<div class="dashboard-wrap">
	<%= link_to "See cats", admin_cats_path, class: "btn btn-lg" %>
	<%= link_to "New cat", new_admin_cat_path, class: "btn btn-lg" %><br>
	<%= link_to "See Bookings", admin_reservations_path, class: "btn btn-lg" %>
</div>

app/views/admin/reservations/index.html.erb
<% @reversations_on_dates.each do |date, reservations| %>
	<h1><%= date %></h1>
	<ul>
		<% reservations.each do |reservation| %>
			<li>
				<%= reservation.cat.name %> is reserved by <%= reservation.name %> from <%= reservation.starts_at.strftime('%d/%m/%Y, %H:%M ') %> to <%= reservation.ends_at.strftime('%H:%M ') %>
			</li>
		<% end %>
	</ul>
<% end %>

app/views/audios/show.js.erb
var html = "<audio controls autoplay style='position: absolute; left: -999px'><source src='/<%= @path %>' type='audio/wav'>Your browser does not support the audio element.</audio>";
$("body").append(html);

app/views/cats/edit.html.erb
<%= form_for @cat do |f| %>
<div class="form-group">
	<%= f.label :name%>
	<%= f.text_field :name, class: "form-control" %>
</div>

<div>
	<%= f.label :male, "Male?"%><br>
	<%= f.check_box :male %>
	<span>Uncheck if cat female</span>
</div>
	<br>
<div class="form-group">	
	<%= f.label :birthdate%>
	<%= f.date_field :birthdate, class: "form-control" %>
</div>
<div class="form-group">	
	<%= f.label :image_url%>
	<%= f.url_field :image_url, class: "form-control" %>
</div>
<div class="form-group">	
	<%= f.label :description%>
	<%= f.text_area :description, class: "form-control" %>
</div>	
	<%= f.submit :class => 'btn btn-primary btn-lg' %>
<% end %>

app/views/cats/index.html.erb
<h2>Catalog <i class="fa fa-paw" aria-hidden="true"></i></h2>
<p>Here you can browse through all our available cat and find your perfect buddy!</p>

<% if @cats.present? %>
	<div class="catalog">
	<% @cats.each do |cat| %>
		<div class="catalog-cat">
			
			<div class="cat-picture" style="background: url('<%= cat.picture.url %>') no-repeat center center;"></div>
			
			<h3><%= link_to cat.name, cat %></h3>
			
				<span class="right">
					<% if cat.male %>
						<i class="fa fa-mars" aria-hidden="true"></i>
					<% else  %>
						<i class="fa fa-venus" aria-hidden="true"></i>
					<% end  %>
				</span>
			<p><%= cat.description %></p>			
			<%= link_to "Book", new_cat_reservation_path(cat), class: "btn btn-primary" %>
		</div>
	<% end%>
</div>
<% else %>
	<p> There are no cats yet.</p>
<% end %>

app/views/cats/new.html.erb
<%= form_for @cat do |f| %>
<div class="form-group">
	<%= f.label :name%>
	<%= f.text_field :name, class: "form-control" %>
</div>

<div>
	<%= f.label :male, "Male?"%><br>
	<%= f.check_box :male %>
	<span>Uncheck if cat female</span>
</div>
	<br>
<div class="form-group">	
	<%= f.label :birthdate%>
	<%= f.date_field :birthdate, class: "form-control" %>
</div>
<div class="form-group">	
	<%= f.label :image_url%>
	<%= f.url_field :image_url, class: "form-control" %>
</div>
<div class="form-group">	
	<%= f.label :description%>
	<%= f.text_area :description, class: "form-control" %>
</div>	
	<%= f.submit :class => 'btn btn-primary btn-lg' %>
<% end %>

app/views/cats/show.html.erb
<h2><%= @cat.name %></h2>

<div class="single-cat-wrapper">

	<div class="cat-picture" style="background: url('<%= @cat.picture.url %>') no-repeat center center;"></div>
	
	<div class="single-cat-info">
		<p><b>Gender:</b> 
			<% if @cat.male %>
				<i class="fa fa-mars" aria-hidden="true"></i>
			<% else  %>
				<i class="fa fa-venus" aria-hidden="true"></i>
			<% end  %>
		</p>
	  <p>
			<b>Birthday:</b>
			<% if @cat.birthdate.present? %>
				<%= @cat.birthdate.strftime("%B %d, %Y") %>
			<% else %>
			  Unknown
			<% end %>
		</p>
		<p>
			<b>Description:</b>
			<% if @cat.description.present? %>
				<%= @cat.description %>
			<% else %>
				No description
			<% end %>
		</p>
		<% if @cat.description.present? %>
			 <!--put back: link_to "Read description aloud", cat_audio_path(@cat), remote: true  -->
		<% end %>
	</div>

</div>
<br>

<%= link_to "Book", new_cat_reservation_path(@cat), class: "btn btn-primary btn-lg" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cat Me!</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash.notice.present? %>
		<div class="alert alert-success alert-dismissible" role="alert">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		  <%= flash.notice %>
		</div>
	<% end %>
	
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
				<%= link_to "CatMe!", root_path, class: "navbar-brand" %>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><%= link_to "Catalog", cats_path %></li>
	        <li><%= link_to "Home", root_path %></li>
	      </ul>
				
	      <ul class="nav navbar-nav navbar-right">
	        <li><%= link_to "Admin", admin_path %></li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	
	<%= image_tag("logo.png", :class => "logo right") %>
	
	
<div class="container">


<%= yield %>


</div>

<!-- <footer>&copy; <%= Time.now.year %></footer> -->
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

app/views/reservations/new.html.erb
<h3>You chose to book an appointment with <%= @cat.name %></h3>
<p>Put in your credentials and choose the time that best suites you.<br>Payment upon arrival (150kr. per appointment)</p>

<%= form_for [@cat, @reservation] do |f| %>
	<div class="form-group">
		<%= f.label :name, "Your name" %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :email, "Your email" %>
		<%= f.email_field :email, class: "form-control" %>
	</div>

	<div class="form-group">
		<input type="date" class="time-slots-date form-control" data-cat-id="<%= @cat.id %>">
	</div>

	<div class="form-group">	
		<%= f.label :starts_at, "Time" %>

		<%= f.select(
			:starts_at,
			@cat.open_slots_for_select(Date.today),
			{ include_blank: true },
			{ class: "form-control time-slot-select" }
		) %>
		<span>Every appointment is 30 minutes.</span>
	</div>

	<%= f.submit :class => 'btn btn-primary btn-lg' %>	
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to CatMe!</h1>


<h3>Feeling lonely and sad? Need some cuddles and kitty lovings?</h3>

<h4>Here you can book some time with one of our feline care takers.</h4>

<div class="intro-text-wrap">
<p>"Pets offer an unconditional love that can be very helpful to people with depression," says Ian Cook, MD, a psychiatrist and director of the Depression Research and Clinic Program at UCLA.</p>

<p>Studies show that people feel better when they have physical contact with others. Pets offer something similar. There's something naturally soothing about petting a cat on your lap.</p>

<p>They help you cope. Cats have been shown to help people get over their loss more quickly, and show less physical symptoms of pain, like crying. Depression can isolate you. It can make you pull back from your friends and loved ones. Despite the fact that they are only animals, cats serve as a social support during difficult times.</p>

<p>Cats in particular also lower your stress level and lower the amount of anxiety in your life. Petting a cat has a positive calming effect.</p>

<br>
<p>Browse through our cats <%= link_to "here", cats_path %>.</p>

</div>

<div class="comic-of-the-week">
	<h6>Have a tiny Cheer-Up <br> - Comic of the Week</h6>
	<img src="<%= @comic["img"] %>">
</div>